### ISSUE TITLE
css实现强制不换行/自动换行/强制换行

### ISSUE THREAD

**Issue by xiaoda** [xiaoda/codediary#42]
强制不换行
```css
div{
    white-space: nowrap;
}
```

自动换行
```css
div{
    word-wrap: break-word; 
    word-break: normal; 
}
```

强制英文单词断行
```css
div{
    word-break:break-all;
}
```

from <a href="http://www.iwms.net/n1919c40.aspx" target="_blank">iwms</a>
